apiVersion: v1
kind: PersistentVolume
metadata:
  name: webservice-volume
  labels:
    type: local
    app: blur
spec:
  storageClassName: local
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/docker/source-images"