apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: webservice-pvc
spec:
  storageClassName: local
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      type: local
      app: blur