apiVersion: v1
kind: Secret
metadata:
  name: webservice-secrets
type: Opaque
data: 
  mysql_user: Ymx1ci11c2Vy
  mysql_password: Ymx1ci1wYXNzd29yZA==
  mysql_root_password: cm9vdC1wYXNzd29yZA== 
  mysql_database: bWV0YWRhdGEtZGF0YWJhc2U=
  # mysql_metadata_table: c291cmNlX2ltYWdlc19tZXRhZGF0YQ==